# Generated by Django 5.2.9 on 2026-01-03 11:52

import chat.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=chat.models.user_directory_path,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sender_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message_send", "Message Sent"),
                            ("message_read", "Message Read"),
                            ("file_upload", "File Uploaded"),
                            ("file_download", "File Downloaded"),
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                            ("validation_failed", "Validation Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="status",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "User Status",
                "verbose_name_plural": "User Statuses",
                "indexes": [
                    models.Index(
                        fields=["is_online"], name="chat_userst_is_onli_6d56ba_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "receiver", "-timestamp"],
                name="chat_messag_sender__44dfd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "sender", "-timestamp"],
                name="chat_messag_receive_7a3702_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read"], name="chat_messag_is_read_872c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-timestamp"], name="chat_messag_timesta_d8d4a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["deleted"], name="chat_messag_deleted_4f3605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["-timestamp"], name="chat_securi_timesta_4c5ccb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="chat_securi_user_id_ce2910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="chat_securi_event_t_3d8402_idx",
            ),
        ),
    ]
