# Generated by Django 5.2.9 on 2026-01-02 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userstatus_message_chat_messag_is_read_872c73_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_sender__53da58_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "receiver", "-timestamp"],
                name="chat_messag_sender__44dfd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "sender", "-timestamp"],
                name="chat_messag_receive_7a3702_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-timestamp"], name="chat_messag_timesta_d8d4a4_idx"
            ),
        ),
    ]
